# Workload A (50/50 for read/write)
# init (write transaction) & query (read transaction)
test:
  workers:
    type: local
    number: 5
  rounds:
    - label: init
      txNumber: 500
      rateControl:
        type: fixed-rate
        opts:
          tps: 25
      workload:
        module: benchmarks/samples/fabric/marbles/init.js
    - label: query
      txDuration: 15
      rateControl:
        type: fixed-rate
        opts:
          tps: 33
      workload:
        module: benchmarks/samples/fabric/marbles/query.js
