# Use the IP address of the AWS instance or machine
version: '3'

networks:
  mongoCluster:
    driver: bridge
    ipam:
      config:
        - subnet: 34.230.30.0/24
          gateway: 34.230.30.141

services:


  primary:
    container_name: primary
    image: mongo:5
    command: mongod --port 27017 --replSet myReplicaSet
    networks:
       mongoCluster:
        ipv4_address: 34.230.30.142

    ports:
      - 27017
    
  secondary1:
    container_name: secondary1
    command: mongod --port 27017 --replSet myReplicaSet
    image: mongo:5
    networks:
       mongoCluster:
        ipv4_address: 34.230.30.143
    ports:
      - 27017
    
  secondary2:
    container_name: secondary2
    image: mongo:5
    command: mongod --port 27017 --replSet myReplicaSet
    networks:
       mongoCluster:
         ipv4_address: 34.230.30.144
    ports:
      - 27017

  secondary3:
    container_name: secondary3
    command: mongod --port 27017 --replSet myReplicaSet
    image: mongo:5
    networks:
       mongoCluster:
        ipv4_address: 34.230.30.145
    ports:
      - 27017

