# Workload C (100/0 for read/write)
# init (write transaction) & query (read transaction)
test:
  workers:
    type: local
    number: 5
  rounds:
    - label: init
      txNumber: 0.3
      rateControl:
        type: fixed-rate
        opts:
          tps: 0
      workload:
        module: benchmarks/samples/fabric/marbles/init.js
    - label: query
      txDuration: 41.35
      rateControl:
        type: fixed-rate
        opts:
          tps: 24
      workload:
        module: benchmarks/samples/fabric/marbles/query.js
